package com.acc.gitlab.bot.service;

import com.acc.gitlab.bot.client.GitLabApiClient;
import com.acc.gitlab.bot.dto.GitLabMergeRequestChanges;
import com.acc.gitlab.bot.dto.GitLabWebhookEvent;
import com.acc.gitlab.bot.properties.GitLabBotProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class GitLabBotService {

    private final GitLabApiClient gitLabApiClient;
    private final ClaudeService claudeService;
    private final GitLabBotProperties gitLabBotProperties;

    public void handleWebhookEvent(GitLabWebhookEvent event) {
        log.info("Received webhook event: {}", event.getObjectKind());

        if (!"note".equals(event.getObjectKind())) {
            log.info("Ignoring non-note event");
            return;
        }

        if (!"MergeRequest".equals(event.getObjectAttributes().getNoteableType())) {
            log.info("Ignoring non-MR note");
            return;
        }

        String comment = event.getObjectAttributes().getNote();
        if (!isBotMentioned(comment)) {
            log.info("Bot not mentioned in comment, ignoring");
            return;
        }

        log.info("Bot mentioned in MR comment, processing...");

        Long projectId = event.getProject().getId();
        Long mergeRequestIid = event.getMergeRequest().getIid();

        try {
            GitLabMergeRequestChanges changes = gitLabApiClient.getMergeRequestChanges(projectId, mergeRequestIid);

            String diff = extractDiffFromChanges(changes);

            if (diff == null || diff.isBlank()) {
                gitLabApiClient.postComment(projectId, mergeRequestIid,
                        "변경 사항이 없어서 리뷰할 내용이 없습니다.");
                return;
            }

            String reviewCommand = extractReviewCommand(comment);
            String review = performReview(diff, reviewCommand);

            String formattedReview = formatReviewComment(review);
            gitLabApiClient.postComment(projectId, mergeRequestIid, formattedReview);

            log.info("Code review completed and posted successfully");

        } catch (Exception e) {
            log.error("Error during code review process", e);
            gitLabApiClient.postComment(projectId, mergeRequestIid,
                    "코드 리뷰 중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    private boolean isBotMentioned(String comment) {
        String botMention = "@" + gitLabBotProperties.getBotUsername();
        return comment != null && comment.toLowerCase().contains(botMention.toLowerCase());
    }

    private String extractReviewCommand(String comment) {
        String lowerComment = comment.toLowerCase();

        if (lowerComment.contains("보안")) {
            return "security";
        } else if (lowerComment.contains("성능")) {
            return "performance";
        } else if (lowerComment.contains("테스트")) {
            return "test";
        }

        return "general";
    }

    private String performReview(String diff, String reviewCommand) {
        return claudeService.reviewCode(diff);
    }

    private String extractDiffFromChanges(GitLabMergeRequestChanges changes) {
        if (changes.getChanges() == null || changes.getChanges().isEmpty()) {
            return null;
        }

        return changes.getChanges().stream()
                .map(change -> {
                    StringBuilder sb = new StringBuilder();
                    sb.append("File: ").append(change.getNewPath()).append("\n");
                    if (Boolean.TRUE.equals(change.getNewFile())) {
                        sb.append("(New File)\n");
                    } else if (Boolean.TRUE.equals(change.getDeletedFile())) {
                        sb.append("(Deleted File)\n");
                    } else if (Boolean.TRUE.equals(change.getRenamedFile())) {
                        sb.append("(Renamed from: ").append(change.getOldPath()).append(")\n");
                    }
                    sb.append(change.getDiff()).append("\n");
                    return sb.toString();
                })
                .collect(Collectors.joining("\n---\n"));
    }

    private String formatReviewComment(String review) {
        return """
                ## Claude 코드 리뷰

                %s

                ---
                *Generated by Claude Code Review Bot*
                """.formatted(review);
    }
}