package com.acc.global.exception.network;

import com.acc.global.exception.ErrorCode;
import lombok.Getter;

@Getter
public enum NeutronErrorCode implements ErrorCode {

    NEUTRON_FLOATING_IP_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-FLOATING-IP-CREATION-FAILED", "Neutron 플로팅 IP 생성에 실패했습니다."),
    NEUTRON_FLOATING_IP_RELEASE_FAILED(500, "ACC-NETWORK-NEUTRON-FLOATING-IP-RELEASE-FAILED", "Neutron 플로팅 IP 해제에 실패했습니다."),
    NEUTRON_FLOATING_IP_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-FLOATING-IP-RETRIEVAL-FAILED", "Neutron 플로팅 IP 조회에 실패했습니다."),
    NEUTRON_FLOATING_IP_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-FLOATING-IP-BAD-REQUEST", "Neutron 플로팅 IP 요청이 잘못되었습니다."),
    NEUTRON_FLOATING_IP_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-FLOATING-IP-FORBIDDEN", "Neutron 플로팅 IP 접근이 금지되었습니다."),
    NEUTRON_FLOATING_IP_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-FLOATING-IP-NOT-FOUND", "Neutron 플로팅 IP를 찾을 수 없습니다."),

    NEUTRON_PORT_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-PORT-CREATION-FAILED", "Neutron 포트 생성에 실패했습니다."),
    NEUTRON_PORT_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-PORT-DELETION-FAILED", "Neutron 포트 삭제에 실패했습니다."),
    NEUTRON_PORT_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-PORT-RETRIEVAL-FAILED", "Neutron 포트 조회에 실패했습니다."),
    NEUTRON_PORT_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-PORT-BAD-REQUEST", "Neutron 포트 요청이 잘못되었습니다."),
    NEUTRON_PORT_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-PORT-FORBIDDEN", "Neutron 포트 접근이 금지되었습니다."),
    NEUTRON_PORT_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-PORT-NOT-FOUND", "Neutron 포트를 찾을 수 없습니다."),
    NEUTRON_PORT_NETWORK_RESOURCE_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-PORT-NETWORK-RESOURCE-NOT-FOUND", "Neutron 포트의 네트워크 관련 리소스를 찾을 수 없습니다."),

    NEUTRON_ROUTER_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-ROUTER-CREATION-FAILED", "Neutron 라우터 생성에 실패했습니다."),
    NEUTRON_ROUTER_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-ROUTER-DELETION-FAILED", "Neutron 라우터 삭제에 실패했습니다."),
    NEUTRON_ROUTER_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-ROUTER-RETRIEVAL-FAILED", "Neutron 라우터 조회에 실패했습니다."),
    NEUTRON_ROUTER_CONNECT_SUBNET_FAILED(500, "ACC-NETWORK-NEUTRON-ROUTER-CONNECT-SUBNET-FAILED", "Neutron 라우터와 서브넷 연결에 실패했습니다."),
    NEUTRON_ROUTER_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-ROUTER-BAD-REQUEST", "Neutron 라우터 요청이 잘못되었습니다."),
    NEUTRON_ROUTER_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-ROUTER-FORBIDDEN", "Neutron 라우터 접근이 금지되었습니다."),
    NEUTRON_ROUTER_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-ROUTER-NOT-FOUND", "Neutron 라우터를 찾을 수 없습니다."),
    NEUTRON_ROUTER_DISCONNECT_SUBNET_FAILED(500, "ACC-NETWORK-NEUTRON-ROUTER-DISCONNECT-SUBNET-FAILED", "Neutron 라우터와 서브넷 연결 해제에 실패했습니다."),
    NEUTRON_ROUTER_CONFLICT(409, "ACC-NETWORK-NEUTRON-ROUTER-CONFLICT", "Neutron 라우터 상태가 충돌했습니다."),

    NEUTRON_SUBNET_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-SUBNET-CREATION-FAILED", "Neutron 서브넷 생성에 실패했습니다."),
    NEUTRON_SUBNET_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-SUBNET-DELETION-FAILED", "Neutron 서브넷 삭제에 실패했습니다."),
    NEUTRON_SUBNET_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-SUBNET-RETRIEVAL-FAILED", "Neutron 서브넷 조회에 실패했습니다."),
    NEUTRON_SUBNET_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-SUBNET-BAD-REQUEST", "Neutron 서브넷 요청이 잘못되었습니다."),
    NEUTRON_SUBNET_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-SUBNET-FORBIDDEN", "Neutron 서브넷 접근이 금지되었습니다."),
    NEUTRON_SUBNET_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-SUBNET-NOT-FOUND", "Neutron 서브넷을 찾을 수 없습니다."),
    NEUTRON_SUBNET_UNAUTHORIZED(401, "ACC-NETWORK-NEUTRON-SUBNET-UNAUTHORIZED", "Neutron 서브넷 접근이 인증되지 않았습니다."),

    NEUTRON_NETWORK_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-NETWORK-CREATION-FAILED", "Neutron 네트워크 생성에 실패했습니다."),
    NEUTRON_NETWORK_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-NETWORK-DELETION-FAILED", "Neutron 네트워크 삭제에 실패했습니다."),
    NEUTRON_NETWORK_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-NETWORK-RETRIEVAL-FAILED", "Neutron 네트워크 조회에 실패했습니다."),
    NEUTRON_NETWORK_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-NETWORK-BAD-REQUEST", "Neutron 네트워크 요청이 잘못되었습니다."),
    NEUTRON_NETWORK_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-NETWORK-FORBIDDEN", "Neutron 네트워크 접근이 금지되었습니다."),
    NEUTRON_NETWORK_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-NETWORK-NOT-FOUND", "Neutron 네트워크를 찾을 수 없습니다."),

    NEUTRON_SECURITY_GROUP_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-CREATION-FAILED", "Neutron 보안 그룹 생성에 실패했습니다."),
    NEUTRON_SECURITY_GROUP_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-DELETION-FAILED", "Neutron 보안 그룹 삭제에 실패했습니다."),
    NEUTRON_SECURITY_GROUP_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-RETRIEVAL-FAILED", "Neutron 보안 그룹 조회에 실패했습니다."),
    NEUTRON_SECURITY_GROUP_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-BAD-REQUEST", "Neutron 보안 그룹 요청이 잘못되었습니다."),
    NEUTRON_SECURITY_GROUP_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-FORBIDDEN", "Neutron 보안 그룹 접근이 금지되었습니다."),
    NEUTRON_SECURITY_GROUP_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-SECURITY-GROUP-NOT-FOUND", "Neutron 보안 그룹을 찾을 수 없습니다."),

    NEUTRON_SECURITY_RULE_CREATION_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-RULE-CREATION-FAILED", "Neutron 보안 규칙 생성에 실패했습니다."),
    NEUTRON_SECURITY_RULE_DELETION_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-RULE-DELETION-FAILED", "Neutron 보안 규칙 삭제에 실패했습니다."),
    NEUTRON_SECURITY_RULE_RETRIEVAL_FAILED(500, "ACC-NETWORK-NEUTRON-SECURITY-RULE-RETRIEVAL-FAILED", "Neutron 보안 규칙 조회에 실패했습니다."),
    NEUTRON_SECURITY_RULE_BAD_REQUEST(400, "ACC-NETWORK-NEUTRON-SECURITY-RULE-BAD-REQUEST", "Neutron 보안 규칙 요청이 잘못되었습니다."),
    NEUTRON_SECURITY_RULE_FORBIDDEN(403, "ACC-NETWORK-NEUTRON-SECURITY-RULE-FORBIDDEN", "Neutron 보안 규칙 접근이 금지되었습니다."),
    NEUTRON_SECURITY_RULE_NOT_FOUND(404, "ACC-NETWORK-NEUTRON-SECURITY-RULE-NOT-FOUND", "Neutron 보안 규칙을 찾을 수 없습니다.");

    private final int status;
    private final String code;
    private final String message;

    NeutronErrorCode(int status, String code, String message) {
        this.status = status;
        this.code = code;
        this.message = message;
    }
}
