import json
import os
import textwrap
import urllib.error
import urllib.request


def get_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"[claude-review] Required environment variable missing: {name}")
    return value


def http_request(
    method: str,
    url: str,
    headers: dict | None = None,
    body: dict | None = None,
) -> dict:
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        if headers is None:
            headers = {}
        headers = {**headers, "Content-Type": "application/json"}

    req = urllib.request.Request(url, data=data, headers=headers or {}, method=method)

    try:
        with urllib.request.urlopen(req) as resp:
            charset = resp.headers.get_content_charset() or "utf-8"
            text = resp.read().decode(charset)
    except urllib.error.HTTPError as e:
        # Debug logging for 4xx/5xx responses (including Anthropic / proxy errors)
        body_text = e.read().decode("utf-8", errors="replace")
        print(f"[claude-review] HTTPError {e.code} {e.reason}")
        print("[claude-review] Response headers:", dict(e.headers.items()))
        print("[claude-review] Response body (first 1000 chars):")
        print(body_text[:1000])
        raise

    if not text:
        return {}
    return json.loads(text)


def get_mr_diff() -> str:
    gitlab_api = (os.environ.get("CI_API_V4_URL") or "https://gitlab.com/api/v4").rstrip("/")
    project_id = get_env("CI_PROJECT_ID")
    mr_iid = get_env("CI_MERGE_REQUEST_IID")
    token = get_env("GITLAB_ACCESS_TOKEN")

    url = f"{gitlab_api}/projects/{project_id}/merge_requests/{mr_iid}/changes"
    data = http_request(
        "GET",
        url,
        headers={"PRIVATE-TOKEN": token},
    )

    parts: list[str] = []
    for change in data.get("changes", []):
        header = f"File: {change.get('new_path')}\n"
        if change.get("new_file"):
            header += "(New File)\n"
        elif change.get("deleted_file"):
            header += "(Deleted File)\n"
        elif change.get("renamed_file"):
            header += f"(Renamed from: {change.get('old_path')})\n"
        diff = change.get("diff") or ""
        parts.append(header + diff)

    return "\n---\n".join(parts)


def build_prompt(diff: str) -> str:
    return textwrap.dedent(
        f"""
        다음 코드 변경사항을 리뷰해주세요.

        리뷰 시 다음 사항들을 중점적으로 확인해주세요:
        1. 버그나 잠재적인 오류 가능성
        2. 코드 품질 및 가독성
        3. 보안 취약점 (SQL Injection, XSS 등)
        4. 성능 이슈
        5. 모범 사례 준수 여부

        코드 변경사항:
        ```
        {diff}
        ```

        리뷰는 한국어로 작성해주시고, 구체적이고 실행 가능한 피드백을 제공해주세요.
        긍정적인 부분도 함께 언급해주세요.
        """
    ).strip()


def call_claude(prompt: str) -> str:
    api_key = get_env("ANTHROPIC_API_KEY")
    model = os.environ.get("CLAUDE_MODEL", "claude-3-5-sonnet-latest")
    max_tokens = int(os.environ.get("CLAUDE_MAX_TOKENS", "4000"))

    body = {
        "model": model,
        "max_tokens": max_tokens,
        "messages": [
            {
                "role": "user",
                "content": prompt,
            }
        ],
    }

    data = http_request(
        "POST",
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        body=body,
    )

    content = data.get("content") or []
    if not content:
        return "리뷰 결과를 파싱할 수 없습니다."

    first = content[0]
    text = first.get("text")
    if not isinstance(text, str) or not text.strip():
        return "리뷰 결과를 파싱할 수 없습니다."

    return text


def post_comment(review: str) -> None:
    gitlab_api = (os.environ.get("CI_API_V4_URL") or "https://gitlab.com/api/v4").rstrip("/")
    project_id = get_env("CI_PROJECT_ID")
    mr_iid = get_env("CI_MERGE_REQUEST_IID")
    token = get_env("GITLAB_ACCESS_TOKEN")

    url = f"{gitlab_api}/projects/{project_id}/merge_requests/{mr_iid}/notes"
    body = {
        "body": textwrap.dedent(
            f"""
            ## Claude 코드 리뷰

            {review}

            ---
            _Generated by Claude Code Review Bot (GitLab CI)_
            """
        ).strip()
    }

    http_request(
        "POST",
        url,
        headers={"PRIVATE-TOKEN": token},
        body=body,
    )


def main() -> None:
    diff = get_mr_diff()
    if not diff.strip():
        post_comment("변경 사항이 없어서 리뷰할 내용이 없습니다.")
        return

    prompt = build_prompt(diff)
    review = call_claude(prompt)
    post_comment(review)


if __name__ == "__main__":
    main()
